# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-14 19:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(3)])),
                ('sexo', models.CharField(choices=[(b'M', b'Masculino'), (b'F', b'Feminino')], default=b'M', max_length=2)),
                ('localidade', models.CharField(max_length=500)),
                ('escola', models.IntegerField(choices=[(0, b'P\xc3\xbablica'), (1, b'Privada')], default=0)),
                ('jogo', models.IntegerField(choices=[(0, b'Plataforma'), (1, b'Slingshot Challenge')], default=0)),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rodadas', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(3)])),
                ('ponto_coop', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(2)])),
                ('ponto_nao_coop', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(1)])),
                ('dificuldade', models.IntegerField(choices=[(0, b'F\xc3\xa1cil'), (1, b'M\xc3\xa9dio'), (2, b'Dif\xc3\xadcil')], default=0)),
                ('estrategia', models.IntegerField(choices=[(0, b'Sempre Coopera'), (1, b'Nunca Coopera'), (2, b'Coopera e repete a \xc3\xbaltima jogada'), (3, b'Coopera e repete a \xc3\xbaltima jogada, duas rodadas seguidas para n\xc3\xa3o cooperar'), (4, b'Aleat\xc3\xb3rio'), (10, b'Multiplayer')], default=4)),
                ('jogo', models.IntegerField(choices=[(0, b'Plataforma'), (1, b'Slingshot Challenge')], default=0)),
                ('jogador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partida_jogador_1', to='hello.Jogador')),
                ('jogador2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partida_jogador_2', to='hello.Jogador')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('pontuacao_jogador1', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('pontuacao_jogador2', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('cooperacao_jogador1', models.IntegerField(choices=[(0, b'Cooperou'), (1, b'N\xc3\xa3o Cooperou')], default=0)),
                ('cooperacao_jogador2', models.IntegerField(choices=[(0, b'Cooperou'), (1, b'N\xc3\xa3o Cooperou')], default=0)),
                ('jogo', models.IntegerField(choices=[(0, b'Plataforma'), (1, b'Slingshot Challenge')], default=0)),
                ('id_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Partida')),
            ],
            options={
                'verbose_name': 'Rodada',
                'verbose_name_plural': 'Rodadas',
            },
        ),
    ]
