# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170223_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
