# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_jogador_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='id_jogador',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='jogador',
            name='UE4GUID',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
