# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20170308_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='UE4GUID',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rodada',
            name='UE4GUID',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
