# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20170308_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodada',
            name='UE4GUID',
        ),
    ]
