# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20170308_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='quantidade_pontos_cooperacao',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='quantidade_pontos_nao_cooperacao',
        ),
    ]
